server:
  port: 3344

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/leanmTree/spring-cloud-config
#          username:
#          password:
          default-label: main
          search-paths: test/