##暴露端口
#server:
#  port: 8001
#
#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://124.70.157.112:3306/db01?useunicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root
#  application:
#    name: provider
#
#mybatis:
#  type-aliases-package: com.lemon.pojo
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
##  configuration:
##    map-underscore-to-camel-case: true
#
#
##声明eureka注册中心地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka.7001.com:7001/eureka/,http://eureka.7002.com:7002/eureka/,http://eureka.7003.com:7003/eureka/
spring:
  application:
    name: provider-8001