server:
  port: 3344

spring:
  application:
    name: config-server



  cloud:
    config:
      server:
        git:
          uri: https://github.com/leanmTree/spring-cloud-config
#          username: 535745426@qq.com
#          password: wht950808
          default-label: main
          search-paths: test/

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
