server:
  port: 80


spring:
  application:
    name: consumer80

#启动服务降级
feign:
  hystrix:
    enabled: true

eureka:
  client:
    # 针对调用方来说，就不需要向注册中心注册自己了
    #register-with-eureka: false
    service-url:
      defaultZone: http://eureka.7001.com:7001/eureka/,http://eureka.7002.com:7002/eureka/,http://eureka.7003.com:7003/eureka/
#provider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.lemon.consumer.config.MyRule